CREATE TABLE IF NOT EXISTS USERS (
    USERNAME VARCHAR(100) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(250) NOT NULL,
    ACCOUNT_NON_EXPIRED BOOLEAN NOT NULL,
    ACCOUNT_NON_LOCKED BOOLEAN NOT NULL,
    CREDENTIALS_NON_EXPIRED BOOLEAN NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NULL
);